# Generated by Django 5.1.7 on 2025-03-22 17:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='employees/')),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Medicine Manager', 'Medicine Manager'), ('Order Manager', 'Order Manager')], default='Admin', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
